spring.application.name=hospital-management

spring.datasource.url=jdbc:mysql://localhost:3306/hospital?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=${JWT_SECRET}

jwt.expiration.ms=86400000

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000}

app.admin.email=${ADMIN_EMAIL:admin@hospital.com}
app.admin.password=${ADMIN_PASSWORD}